name: Curvenote Preview Draft from PR
on:
  pull_request_target:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/draft.yml@v1
    with:
      id-pattern-regex: '^nucleus-devnote-contrib-(?:[a-zA-Z0-9-_]{3,15})$'
      venue: bnext-devnotes
      kind: dev-notes
      collection: nucleus-contrib
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
