name: Curvenote Submission from Main
on:
  push:
    branches: ['main']
permissions:
  contents: write
jobs:
  submit:
    uses: curvenote/actions/.github/workflows/submit.yml@v1
    with:
      id-pattern-regex: '^nucleus-devnote-contrib-(?:[a-zA-Z0-9-_]{3,15})$'
      venue: bnext-devnotes
      kind: dev-notes
      collection: nucleus-contrib
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
